package com.nirsa.comprobantes.persistencia.bean;
// Generated 29-may-2013 12:11:16 by Hibernate Tools 3.2.1.GA

/**
 * ClaveAcceso generated by hbm2java
 */
public class ClaveAcceso implements java.io.Serializable {

    private int id;
    private String clave;
    private Boolean usada;
    private String codigoComprobante;

    public ClaveAcceso() {
    }

    public ClaveAcceso(int id) {
        this.id = id;
    }

    public ClaveAcceso(int id, String clave, Boolean usada, String codigoComprobante) {
        this.id = id;
        this.clave = clave;
        this.usada = usada;
        this.codigoComprobante = codigoComprobante;
    }

    public int getId() {
        return this.id;
    }

    public void setId(int id) {
        this.id = id;
    }

    public String getClave() {
        return this.clave;
    }

    public void setClave(String clave) {
        this.clave = clave;
    }

    public Boolean getUsada() {
        return this.usada;
    }

    public void setUsada(Boolean usada) {
        this.usada = usada;
    }

    public String getCodigoComprobante() {
        return this.codigoComprobante;
    }

    public void setCodigoComprobante(String codigoComprobante) {
        this.codigoComprobante = codigoComprobante;
    }
}
