package com.nirsa.comprobantes.persistencia.bean;
// Generated 29-may-2013 12:11:16 by Hibernate Tools 3.2.1.GA

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Emisor generated by hbm2java
 */
public class Emisor implements java.io.Serializable {

    private int id;
    private String emisorRuc;
    private String emisorRazonSocial;
    private String emisorNombreComercial;
    private String emisorDireccionMatriz;
    private String emisorDireccionEstablecimiento;
    private String emisorNumeroResolucionContribuyenteEspecial;
    private String emisorObligadoLlevarContabilidad;
    private byte[] emisorLogo;
    private Integer emisorTiempoEspera;
    private String emisorRutaFirmaDigital;
    private Date emisorFechaCreacion;
    private Date emisorFechaModificacion;
    private Character emisorEstaActivo;
    private Set usuarios = new HashSet(0);

    public Emisor() {
    }

    public Emisor(int id) {
        this.id = id;
    }

    public Emisor(int id, String emisorRuc, String emisorRazonSocial, String emisorNombreComercial, String emisorDireccionMatriz, String emisorDireccionEstablecimiento, String emisorNumeroResolucionContribuyenteEspecial, String emisorObligadoLlevarContabilidad, byte[] emisorLogo, Integer emisorTiempoEspera, String emisorRutaFirmaDigital, Date emisorFechaCreacion, Date emisorFechaModificacion, Character emisorEstaActivo, Set usuarios) {
        this.id = id;
        this.emisorRuc = emisorRuc;
        this.emisorRazonSocial = emisorRazonSocial;
        this.emisorNombreComercial = emisorNombreComercial;
        this.emisorDireccionMatriz = emisorDireccionMatriz;
        this.emisorDireccionEstablecimiento = emisorDireccionEstablecimiento;
        this.emisorNumeroResolucionContribuyenteEspecial = emisorNumeroResolucionContribuyenteEspecial;
        this.emisorObligadoLlevarContabilidad = emisorObligadoLlevarContabilidad;
        this.emisorLogo = emisorLogo;
        this.emisorTiempoEspera = emisorTiempoEspera;
        this.emisorRutaFirmaDigital = emisorRutaFirmaDigital;
        this.emisorFechaCreacion = emisorFechaCreacion;
        this.emisorFechaModificacion = emisorFechaModificacion;
        this.emisorEstaActivo = emisorEstaActivo;
        this.usuarios = usuarios;
    }

    public int getId() {
        return this.id;
    }

    public void setId(int id) {
        this.id = id;
    }

    public String getEmisorRuc() {
        return this.emisorRuc;
    }

    public void setEmisorRuc(String emisorRuc) {
        this.emisorRuc = emisorRuc;
    }

    public String getEmisorRazonSocial() {
        return this.emisorRazonSocial;
    }

    public void setEmisorRazonSocial(String emisorRazonSocial) {
        this.emisorRazonSocial = emisorRazonSocial;
    }

    public String getEmisorNombreComercial() {
        return this.emisorNombreComercial;
    }

    public void setEmisorNombreComercial(String emisorNombreComercial) {
        this.emisorNombreComercial = emisorNombreComercial;
    }

    public String getEmisorDireccionMatriz() {
        return this.emisorDireccionMatriz;
    }

    public void setEmisorDireccionMatriz(String emisorDireccionMatriz) {
        this.emisorDireccionMatriz = emisorDireccionMatriz;
    }

    public String getEmisorDireccionEstablecimiento() {
        return this.emisorDireccionEstablecimiento;
    }

    public void setEmisorDireccionEstablecimiento(String emisorDireccionEstablecimiento) {
        this.emisorDireccionEstablecimiento = emisorDireccionEstablecimiento;
    }

    public String getEmisorNumeroResolucionContribuyenteEspecial() {
        return this.emisorNumeroResolucionContribuyenteEspecial;
    }

    public void setEmisorNumeroResolucionContribuyenteEspecial(String emisorNumeroResolucionContribuyenteEspecial) {
        this.emisorNumeroResolucionContribuyenteEspecial = emisorNumeroResolucionContribuyenteEspecial;
    }

    public String getEmisorObligadoLlevarContabilidad() {
        return this.emisorObligadoLlevarContabilidad;
    }

    public void setEmisorObligadoLlevarContabilidad(String emisorObligadoLlevarContabilidad) {
        this.emisorObligadoLlevarContabilidad = emisorObligadoLlevarContabilidad;
    }

    public byte[] getEmisorLogo() {
        return this.emisorLogo;
    }

    public void setEmisorLogo(byte[] emisorLogo) {
        this.emisorLogo = emisorLogo;
    }

    public Integer getEmisorTiempoEspera() {
        return this.emisorTiempoEspera;
    }

    public void setEmisorTiempoEspera(Integer emisorTiempoEspera) {
        this.emisorTiempoEspera = emisorTiempoEspera;
    }

    public String getEmisorRutaFirmaDigital() {
        return this.emisorRutaFirmaDigital;
    }

    public void setEmisorRutaFirmaDigital(String emisorRutaFirmaDigital) {
        this.emisorRutaFirmaDigital = emisorRutaFirmaDigital;
    }

    public Date getEmisorFechaCreacion() {
        return this.emisorFechaCreacion;
    }

    public void setEmisorFechaCreacion(Date emisorFechaCreacion) {
        this.emisorFechaCreacion = emisorFechaCreacion;
    }

    public Date getEmisorFechaModificacion() {
        return this.emisorFechaModificacion;
    }

    public void setEmisorFechaModificacion(Date emisorFechaModificacion) {
        this.emisorFechaModificacion = emisorFechaModificacion;
    }

    public Character getEmisorEstaActivo() {
        return this.emisorEstaActivo;
    }

    public void setEmisorEstaActivo(Character emisorEstaActivo) {
        this.emisorEstaActivo = emisorEstaActivo;
    }

    public Set getUsuarios() {
        return this.usuarios;
    }

    public void setUsuarios(Set usuarios) {
        this.usuarios = usuarios;
    }
}
